package com.cloudbuilder.docs.domain.model;

import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "doc_metadata")
public class DocMetadata {

    @Id
    private String id;

    @Column(nullable = false)
    private String tenantId;

    @Column(nullable = false)
    private String path;

    @Column
    private String title;

    @Column(name = "sha256_checksum")
    private String sha256Checksum;

    @Column(columnDefinition = "TEXT")
    private String content;

    @Column
    private Instant lastModified;

    @Column(nullable = false)
    private Instant importedAt;

    @Column
    private boolean stale;

    @Column
    private boolean autoGenerated;

    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @Column(nullable = false)
    private Instant updatedAt;

    protected DocMetadata() {}

    public DocMetadata(String tenantId, String path, String title) {
        this.id = UUID.randomUUID().toString();
        this.tenantId = tenantId;
        this.path = path;
        this.title = title;
        this.importedAt = Instant.now();
        this.createdAt = Instant.now();
        this.updatedAt = Instant.now();
    }

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getTenantId() { return tenantId; }
    public void setTenantId(String tenantId) { this.tenantId = tenantId; }

    public String getPath() { return path; }
    public void setPath(String path) { this.path = path; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getSha256Checksum() { return sha256Checksum; }
    public void setSha256Checksum(String sha256Checksum) { this.sha256Checksum = sha256Checksum; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public Instant getLastModified() { return lastModified; }
    public void setLastModified(Instant lastModified) { this.lastModified = lastModified; }

    public Instant getImportedAt() { return importedAt; }
    public void setImportedAt(Instant importedAt) { this.importedAt = importedAt; }

    public boolean isStale() { return stale; }
    public void setStale(boolean stale) { this.stale = stale; }

    public boolean isAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

    public Instant getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(Instant updatedAt) { this.updatedAt = updatedAt; }
}
