package grpc

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/cloudbuilder/provision-engine/internal/drift"
	pb "github.com/cloudbuilder/provision-engine/internal/api/grpc/proto"
	"github.com/cloudbuilder/provision-engine/internal/executor"
	"github.com/cloudbuilder/provision-engine/internal/messaging"
	"github.com/cloudbuilder/provision-engine/internal/parser"
)

type ProvisionServer struct {
	pb.UnimplementedProvisionServiceServer
	eventPublisher *messaging.EventPublisher
}

func NewProvisionServer() *ProvisionServer {
	return &ProvisionServer{
		eventPublisher: messaging.NewEventPublisher(),
	}
}

func (s *ProvisionServer) GenerateCode(ctx context.Context, req *pb.GenerateCodeRequest) (*pb.GenerateCodeResponse, error) {
	if req.DesignJson == "" {
		return nil, fmt.Errorf("design_json is required")
	}

	templates := map[string]string{
		"aws_vpc": `resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  tags = { Name = "cb-vpc" }
}`,
		"aws_instance": `resource "aws_instance" "web" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t3.medium"
  subnet_id     = aws_subnet.main.id
}`,
		"aws_subnet": `resource "aws_subnet" "main" {
  vpc_id     = aws_vpc.main.id
  cidr_block = "10.0.1.0/24"
}`,
		"aws_s3_bucket": `resource "aws_s3_bucket" "data" {
  bucket = "cb-data-bucket"
  force_destroy = true
}`,
		"aws_security_group": `resource "aws_security_group" "main" {
  name        = "cb-sg"
  description = "CloudBuilder managed"
  vpc_id      = aws_vpc.main.id
}`,
	}

	resourceCount := int32(0)
	files := map[string]string{
		"main.tf":       "# Generated by CloudBuilder Provision Engine\n\n",
		"variables.tf":  "# Input variables\n\nvariable \"region\" {\n  type    = string\n  default = \"us-east-1\"\n}\n",
		"outputs.tf":    "# Outputs\n\noutput \"vpc_id\" {\n  value = aws_vpc.main.id\n}\n",
		"providers.tf":  "provider \"aws\" {\n  region = var.region\n}\n",
		"versions.tf":   "terraform {\n  required_version = \">= 1.6.0\"\n}\n",
	}

	// Parse design JSON and generate resources
	var design struct {
		Nodes []struct {
			ID           string            `json:"id"`
			ResourceType string            `json:"resourceType"`
			Provider     string            `json:"provider"`
			Properties   map[string]string `json:"properties"`
		} `json:"nodes"`
	}
	if err := json.Unmarshal([]byte(req.DesignJson), &design); err != nil {
		// Return default template if design can't be parsed
		return &pb.GenerateCodeResponse{
			Files:         files,
			ResourceCount: 0,
		}, nil
	}

	var mainBuf string
	for _, node := range design.Nodes {
		tpl, ok := templates[node.ResourceType]
		if !ok {
			tpl = fmt.Sprintf("# No template for %s\nresource \"%s\" \"%s\" {\n  # Custom resource\n}\n", node.ResourceType, node.ResourceType, node.ID)
		}
		mainBuf += tpl + "\n"
		resourceCount++
	}

	if mainBuf == "" {
		mainBuf = "# No resources defined in design\n"
	}
	files["main.tf"] = mainBuf

	return &pb.GenerateCodeResponse{
		Files:         files,
		ResourceCount: resourceCount,
	}, nil
}

func (s *ProvisionServer) ApprovePlan(ctx context.Context, req *pb.ApproveRequest) (*pb.ApproveResponse, error) {
	if req.WorkspaceDir == "" {
		return &pb.ApproveResponse{
			Success: false,
			Error:   "workspace_dir is required",
		}, nil
	}

	engineType := executor.Terraform
	if req.Engine == "opentofu" {
		engineType = executor.OpenTofu
	}

	exe := executor.NewExecutor(engineType, req.WorkspaceDir)
	planFile := filepath.Join(req.WorkspaceDir, "tfplan")

	if _, err := exe.Apply(ctx, planFile); err != nil {
		return &pb.ApproveResponse{
			Success: false,
			Error:   fmt.Sprintf("apply failed: %v", err),
		}, nil
	}

	s.eventPublisher.Publish(ctx, messaging.DeploymentEvent{
		DeploymentID: req.DeploymentId,
		EventType:    messaging.EventDeploymentComplete,
		Status:       "approved",
		Message:      fmt.Sprintf("Plan approved by %s and applied successfully", req.ApprovedBy),
	})

	return &pb.ApproveResponse{
		Success: true,
		Output:  fmt.Sprintf("Plan approved by %s", req.ApprovedBy),
	}, nil
}

func (s *ProvisionServer) Destroy(req *pb.DestroyRequest, stream pb.ProvisionService_DestroyServer) error {
	engineType := executor.Terraform
	if req.Engine == "opentofu" {
		engineType = executor.OpenTofu
	}

	workDir := req.WorkspaceDir
	if workDir == "" {
		workDir = filepath.Join(os.TempDir(), "cloudbuilder", "destroy", req.DeploymentId)
		os.MkdirAll(workDir, 0755)
	}

	exe := executor.NewExecutor(engineType, workDir)
	dm := executor.NewDeploymentManager(exe)

	statusChan := make(chan executor.DeploymentStatus, 10)
	ctx := stream.Context()

	go func() {
		if err := dm.Destroy(ctx, statusChan); err != nil {
			close(statusChan)
		}
	}()

	for status := range statusChan {
		stream.Send(&pb.DestroyEvent{
			DeploymentId: req.DeploymentId,
			EventType:    status.String(),
			Message:      fmt.Sprintf("Destroy status: %s", status),
		})
		if status == executor.StatusDestroyed || status == executor.StatusFailed {
			break
		}
	}

	s.eventPublisher.Publish(ctx, messaging.DeploymentEvent{
		DeploymentID: req.DeploymentId,
		EventType:    messaging.EventDeploymentComplete,
		Status:       "destroyed",
		Message:      "Infrastructure destroyed successfully",
	})

	return nil
}

func (s *ProvisionServer) Deploy(req *pb.DeployRequest, stream pb.ProvisionService_DeployServer) error {
	engineType := executor.Terraform
	if req.Engine == "opentofu" {
		engineType = executor.OpenTofu
	}

	workDir := req.WorkspaceDir
	if workDir == "" {
		workDir = filepath.Join(os.TempDir(), "cloudbuilder", req.DeploymentId)
		os.MkdirAll(workDir, 0755)
	}

	exe := executor.NewExecutor(engineType, workDir)
	dm := executor.NewDeploymentManager(exe)

	statusChan := make(chan executor.DeploymentStatus, 10)
	ctx := stream.Context()

	go func() {
		dm.Execute(ctx, statusChan)
	}()

	for status := range statusChan {
		stream.Send(&pb.DeployEvent{
			DeploymentId: req.DeploymentId,
			EventType:    status.String(),
			Message:      fmt.Sprintf("Deployment status: %s", status),
		})
		if status == executor.StatusPlanned {
			break
		}
		if status == executor.StatusFailed {
			return nil
		}
	}

	return nil
}

func (s *ProvisionServer) GetPlan(ctx context.Context, req *pb.PlanRequest) (*pb.PlanResponse, error) {
	engineType := executor.Terraform
	if req.Engine == "opentofu" {
		engineType = executor.OpenTofu
	}

	exe := executor.NewExecutor(engineType, req.WorkspaceDir)
	planFile := filepath.Join(req.WorkspaceDir, "tfplan")

	if _, err := exe.Init(ctx); err != nil {
		return &pb.PlanResponse{Error: fmt.Sprintf("init failed: %v", err)}, nil
	}

	if _, err := exe.Plan(ctx, planFile); err != nil {
		return &pb.PlanResponse{Error: fmt.Sprintf("plan failed: %v", err)}, nil
	}

	showResult, err := exe.ShowPlan(ctx, planFile)
	if err != nil {
		return &pb.PlanResponse{Error: fmt.Sprintf("show plan failed: %v", err)}, nil
	}

	parsedPlan, err := parser.ParsePlan(showResult.Stdout)
	if err != nil {
		return &pb.PlanResponse{
			PlanJson:   showResult.Stdout,
			HasChanges: true,
			Error:      fmt.Sprintf("parse warning: %v", err),
		}, nil
	}

	added, changed, destroyed := parsedPlan.Summary()
	return &pb.PlanResponse{
		PlanJson:          showResult.Stdout,
		HasChanges:        added+changed+destroyed > 0,
		ResourcesAdded:    int32(added),
		ResourcesChanged:  int32(changed),
		ResourcesDestroyed: int32(destroyed),
	}, nil
}

func (s *ProvisionServer) GetState(ctx context.Context, req *pb.StateRequest) (*pb.StateResponse, error) {
	exe := executor.NewExecutor(executor.Terraform, req.WorkspaceDir)
	result, err := exe.Show(ctx)
	if err != nil {
		return &pb.StateResponse{Error: fmt.Sprintf("show state failed: %v", err)}, nil
	}

	parsedState, err := parser.ParseState(result.Stdout)
	if err != nil {
		return &pb.StateResponse{
			StateJson: result.Stdout,
			Error:     fmt.Sprintf("parse warning: %v", err),
		}, nil
	}

	return &pb.StateResponse{
		StateJson:     result.Stdout,
		ResourceCount: int32(parsedState.ResourceCount()),
	}, nil
}

func (s *ProvisionServer) DetectDrift(ctx context.Context, req *pb.DriftRequest) (*pb.DriftResponse, error) {
	exe := executor.NewExecutor(executor.Terraform, req.WorkspaceDir)
	showResult, err := exe.Show(ctx)
	if err != nil {
		return &pb.DriftResponse{Error: fmt.Sprintf("show state failed: %v", err)}, nil
	}

	report, err := drift.DetectDrift(showResult.Stdout, req.DesignJson)
	if err != nil {
		return &pb.DriftResponse{Error: fmt.Sprintf("drift detection failed: %v", err)}, nil
	}

	resources := make([]*pb.DriftResource, len(report.Resources))
	for i, r := range report.Resources {
		resources[i] = &pb.DriftResource{
			Address:    r.Address,
			Expected:   r.Expected,
			Actual:     r.Actual,
			ChangeType: r.ChangeType,
		}
	}

	return &pb.DriftResponse{
		HasDrift:         report.HasDrift,
		DriftedResources: resources,
	}, nil
}
