#!/usr/bin/env python3
"""Generate a markdown trend report from history.json."""

import json
import sys


def delta(key_path, d):
    """Get a nested value from a dict using dot notation."""
    parts = key_path.split(".")
    v = d
    for p in parts:
        v = v.get(p, 0) if isinstance(v, dict) else 0
    return v or 0


def fmt(v):
    """Format a delta value with + prefix."""
    return f"+{v}" if v > 0 else str(v)


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <history.json> <output.md>")
        sys.exit(1)

    history_path = sys.argv[1]
    output_path = sys.argv[2]

    with open(history_path) as f:
        data = json.load(f)

    if len(data) < 2:
        report = "# Nightly Test Trend Report\n\nNot enough data for trend analysis.\n"
        with open(output_path, "w") as f:
            f.write(report)
        print(report)
        return

    prev = data[-2]
    curr = data[-1]

    b_delta = delta("backend.tests", curr) - delta("backend.tests", prev)
    f_delta = delta("frontend.tests", curr) - delta("frontend.tests", prev)
    g_delta = delta("goEngine.packagesOk", curr) - delta("goEngine.packagesOk", prev)
    total_curr = (
        delta("backend.tests", curr)
        + delta("frontend.tests", curr)
        + delta("goEngine.packagesOk", curr)
    )
    total_prev = (
        delta("backend.tests", prev)
        + delta("frontend.tests", prev)
        + delta("goEngine.packagesOk", prev)
    )
    t_delta = total_curr - total_prev

    report = f"""## 📊 Nightly Test Trend Report

**Date:** {curr["timestamp"][:10]}
**Commit:** `{curr.get("commit", "?")}`
**Branch:** {curr.get("branch", "?")}

### Current vs Previous

| Layer | Current | Previous | Delta |
|-------|---------|----------|-------|
| ☕ Backend | {delta("backend.tests", curr)} | {delta("backend.tests", prev)} | {fmt(b_delta)} |
| ⚛ Frontend | {delta("frontend.tests", curr)} | {delta("frontend.tests", prev)} | {fmt(f_delta)} |
| 🐹 Go Engine | {delta("goEngine.packagesOk", curr)} pkgs | {delta("goEngine.packagesOk", prev)} pkgs | {fmt(g_delta)} |
| **Total** | **{total_curr}** | **{total_prev}** | **{fmt(t_delta)}** |

### Health

| Check | Status |
|-------|--------|
| Backend Failures | {delta("backend.failures", curr) + delta("backend.errors", curr)} |
| Go Engine Fail | {delta("goEngine.packagesFail", curr)} |
| TypeScript Errors | {delta("typescript.errors", curr)} |
| Skipped Tests | {delta("backend.skipped", curr)} |

### 7-Day Trend

| Date | Total | Backend | Frontend | Go |
|------|-------|---------|----------|----|
"""

    recent = data[-7:]
    for d in recent:
        t = (
            delta("backend.tests", d)
            + delta("frontend.tests", d)
            + delta("goEngine.packagesOk", d)
        )
        report += f"| {d['timestamp'][:10]} | {t} | {delta('backend.tests', d)} | {delta('frontend.tests', d)} | {delta('goEngine.packagesOk', d)} |\n"

    report += """
---
*Generated by CloudBuilder Nightly Metrics*
[Dashboard](https://github.com/cloudbuilder/cloudbuilder/blob/main/docs/test-results/dashboard.html)
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    import sys as _sys
    _sys.stdout.reconfigure(encoding="utf-8")
    print(report)


if __name__ == "__main__":
    main()
