package terraform

import (
	"fmt"
	"strings"

	"github.com/cloudbuilder/provision-engine/internal/model"
	"github.com/cloudbuilder/provision-engine/internal/provider/templates"
)

// Generator produces Terraform HCL code from a CanvasDesign.
type Generator struct {
	providerTemplates map[model.ProviderType]map[string]templates.ResourceTemplate
}

// NewGenerator creates a new Generator with built-in template mappings.
func NewGenerator() *Generator {
	return &Generator{
		providerTemplates: make(map[model.ProviderType]map[string]templates.ResourceTemplate),
	}
}

// Generate produces a complete Terraform configuration (.tf file content)
// from the given canvas design.
func (g *Generator) Generate(design model.CanvasDesign) (string, error) {
	var builder strings.Builder

	builder.WriteString(generateHeader())
	builder.WriteString("\n")

	// Track which provider blocks we've already written
	writtenProviders := make(map[model.ProviderType]bool)

	for _, node := range design.Nodes {
		// Write provider block once per provider type
		if !writtenProviders[node.Provider] {
			providerBlock := generateProviderBlock(node.Provider)
			if providerBlock != "" {
				builder.WriteString(providerBlock)
				builder.WriteString("\n")
			}
			writtenProviders[node.Provider] = true
		}

		// Get template and render
		tmpl, ok := templates.GetTemplate(node.Provider, node.Type)
		if !ok {
			builder.WriteString(fmt.Sprintf("# WARNING: No template found for %s/%s\n", node.Provider, node.Type))
			continue
		}

		rendered, err := tmpl(node)
		if err != nil {
			return "", fmt.Errorf("error rendering %s/%s: %w", node.Provider, node.Type, err)
		}
		builder.WriteString(rendered)
		builder.WriteString("\n")
	}

	// Add output blocks for exposed resources
	builder.WriteString(generateOutputBlocks(design.Nodes))

	return builder.String(), nil
}

func generateHeader() string {
	return `# Generated by CloudBuilder Provision Engine
# Terraform configuration - do not edit manually

terraform {
  required_version = ">= 1.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "production"
}

variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

data "aws_availability_zones" "available" {
  state = "available"
}
`
}

func generateProviderBlock(provider model.ProviderType) string {
	switch provider {
	case model.ProviderAWS:
		return `provider "aws" {
  region = var.region
}
`
	case model.ProviderAZURE:
		return `provider "azurerm" {
  features {}
}
`
	case model.ProviderGCP:
		return `provider "google" {
  project = var.project_id
  region  = var.region
}
`
	default:
		return ""
	}
}

func generateOutputBlocks(nodes []model.DesignNode) string {
	var builder strings.Builder

	for _, node := range nodes {
		switch node.Type {
		case "aws_vpc", "vpc":
			builder.WriteString(fmt.Sprintf(`output "vpc_id_%s" {
  value = aws_vpc.%s.id
}

`, node.ID, node.ID))
		case "aws_instance", "instance", "ec2":
			builder.WriteString(fmt.Sprintf(`output "instance_public_ip_%s" {
  value = aws_instance.%s.public_ip
}

`, node.ID, node.ID))
		case "aws_s3_bucket", "s3":
			builder.WriteString(fmt.Sprintf(`output "bucket_arn_%s" {
  value = aws_s3_bucket.%s.arn
}

`, node.ID, node.ID))
		}
	}

	return builder.String()
}
