package com.cloudbuilder.iam.infrastructure.web;

import com.cloudbuilder.iam.domain.model.UserMfa;
import com.cloudbuilder.iam.domain.service.MfaService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

/**
 * Multi-Factor Authentication controller.
 * <p>
 * Per ADR-018: TOTP MFA with backup codes. Uses the authenticated user's identity
 * from the Spring Security context (rather than requiring userId as a path parameter),
 * making it consistent with the self-service MFA pattern.
 * <p>
 * Endpoints:
 * <ul>
 *   <li>{@code POST /api/v1/iam/mfa/setup} — Generate TOTP secret and backup codes</li>
 *   <li>{@code POST /api/v1/iam/mfa/verify} — Verify a TOTP code and enable MFA</li>
 *   <li>{@code POST /api/v1/iam/mfa/disable} — Disable MFA for the current user</li>
 *   <li>{@code GET  /api/v1/iam/mfa/status} — Get MFA configuration status</li>
 * </ul>
 * <p>
 * Note: The {@link IAMController} also has admin-oriented MFA endpoints
 * that operate on arbitrary userId values (e.g., admin resetting another user's MFA).
 * This controller focuses on self-service operations for the authenticated user.
 */
@RestController
@RequestMapping("/api/v1/iam/mfa")
@PreAuthorize("isAuthenticated()")
public class MfaController {

    private final MfaService mfaService;

    public MfaController(MfaService mfaService) {
        this.mfaService = mfaService;
    }

    /**
     * Setup MFA for the current user.
     * Generates a new TOTP secret and backup codes.
     * MFA remains disabled until {@link #verifyMfa(Authentication, VerifyCodeRequest)} is called.
     *
     * @param authentication Spring Security authentication (injected automatically)
     * @return the UserMfa configuration (contains secret for QR code generation)
     */
    @PostMapping("/setup")
    public ResponseEntity<UserMfa> setupMfa(Authentication authentication) {
        String userId = (String) authentication.getPrincipal();
        UserMfa mfa = mfaService.setupMfa(userId);
        return ResponseEntity.ok(mfa);
    }

    /**
     * Verify a TOTP code and enable MFA for the current user.
     * Must be called after {@link #setupMfa(Authentication)} with a valid code
     * generated by the authenticator app.
     *
     * @param authentication Spring Security authentication
     * @param request        the verification code
     * @return the enabled UserMfa configuration
     */
    @PostMapping("/verify")
    public ResponseEntity<UserMfa> verifyMfa(Authentication authentication,
                                              @RequestBody VerifyCodeRequest request) {
        String userId = (String) authentication.getPrincipal();
        UserMfa mfa = mfaService.verifyAndEnable(userId, request.code());
        return ResponseEntity.ok(mfa);
    }

    /**
     * Disable MFA for the current user.
     *
     * @param authentication Spring Security authentication
     * @return 200 OK with confirmation message
     */
    @PostMapping("/disable")
    public ResponseEntity<Map<String, String>> disableMfa(Authentication authentication) {
        String userId = (String) authentication.getPrincipal();
        mfaService.disableMfa(userId);
        return ResponseEntity.ok(Map.of("message", "MFA desabilitado com sucesso"));
    }

    /**
     * Get MFA status for the current user.
     *
     * @param authentication Spring Security authentication
     * @return UserMfa configuration, or 404 if MFA is not configured
     */
    @GetMapping("/status")
    public ResponseEntity<UserMfa> getMfaStatus(Authentication authentication) {
        String userId = (String) authentication.getPrincipal();
        UserMfa mfa = mfaService.getMfaStatus(userId);
        if (mfa == null) {
            return ResponseEntity.notFound().build();
        }
        return ResponseEntity.ok(mfa);
    }

    /**
     * Request body for MFA verification (TOTP code or backup code).
     */
    public record VerifyCodeRequest(String code) {}
}
